### ISSUE TITLE
pod connect the outside host fail

### ISSUE THREAD

**Issue by currycan** [dougbtv/whereabouts#22]
Hello,
     I deploy the whereabouts and multus cni in the k8s cluster. And the cluster run in VM not baremetal，I met a problem that the pod connect the outside host fail, but the outside hosts connect pods well. Is there any special config in VM cluster? Thank you!

**Comment by dougbtv** [comment]
Hey @currycan -- any chance you can provide the CNI configurations for the network attachments? That'd be helpful.

There's no known issues with a VM cluster, and in fact my typical cluster for testing whereabouts is k8s on VMs.

Also if you can also provide a `ip a` and `ip route` for a pod that has trouble with connectivity outside the cluster. Thanks

**Comment by dougbtv** [comment]
Hey @currycan -- any chance you can provide the CNI configurations for the network attachments? That'd be helpful.

There's no known issues with a VM cluster, and in fact my typical cluster for testing whereabouts is k8s on VMs.

Also if you can also provide a `ip a` and `ip route` for a pod that has trouble with connectivity outside the cluster. Thanks

**Comment by currycan** [comment]
@dougbtv Hi, I think there are no problems with the configuration, and there are no problems running on the bare metal host. I used multus + ipvlan + whereabouts to build the pod network, and I was surprised that any virtual IP running on the VM, such as the virtual IP created by keepalived, could not access the host of the Layer 3 network. I wonder if  I  configure the security configuration items of the virtual switch on the VM management controller panel, such as enabling promiscuous mode and enabling pseudo transmission, it would be ok.

**Comment by currycan** [comment]
Hi,
   The problem is solved now, our network engineer set some limitation for the Ips. Thank you all the same.
