### ISSUE TITLE
The "range_end" IP is not available

### ISSUE THREAD

**Issue by clivez** [dougbtv/whereabouts#35]
> range_end : Last IP to use when allocating from the range. 

But actually this last IP is not available, for example if I use the configuration
```
        "range": "192.168.2.0/24",
	"range_start": "192.168.2.10",
	"range_end": "192.168.2.15",
```
only 192.168.2.10-192.168.2.14 can be allocated, 192.168.2.15 is not available.

**Comment by crandles** [comment]
You are correct. Before the range_end parameter was added the allocation code preferred to skip the last IP in the subnet range on the assumption that it is a broadcast address.

I think this was carried over to the range_end parameter, but I do not think it was necessarily the best choice. I'll take a closer look to see if this can be uncoupled.

**Comment by clivez** [comment]
Thank you!
