### ISSUE TITLE
range_end parameter doesn't work with K8S replicaSet.

### ISSUE THREAD

**Issue by KoJJang** [dougbtv/whereabouts#42]
Hello I'm newbie in K8S and multi CNI networking. 

I tested whereabout with below template and conflicted some issue.
```
...
"range": "192.168.2.225/28",
"range_start": "192.168.2.225",
"range_end": "192.168.2.226",
...

```
As you see above, I want to apply IP only in 192.168.2.225 - 192.168.2.226. But when I set in deployment's or statefulset's replicas 3 or over, k8s made pod that have IP over 192.168.2.226 like 192.168.2.227.

I was hoping not to generate a pod on k8s because it was over IP range.

**Comment by KoJJang** [comment]
@crandles 
Yes, I think that change made some confusion. Maybe you intended to include range_end IP to IP Pool. But  below code is making pool more bigger than range_end.
`end = end.Add(end, new(big.Int).SetInt64(1))`

So as @dougbtv mentioned, IP pool will be `range_start - range_end+1`

**Comment by crandles** [comment]
The intent was to make the `range_start - range_end` inclusive (#35), not to allow for range_end+1 IPs. I will try to add some unit tests to highlight this issue.

**Comment by crandles** [comment]
Looks like that was a bad change. See #43 for the fix + tests.
