### ISSUE TITLE
Pod gets stuck in ContainerCreating state if first attempt of CNI ADD fails (Multus CNI, Whereabouts IPAM)

### ISSUE THREAD

**Issue by dougbtv** [dougbtv/whereabouts#70]
See: https://github.com/intel/multus-cni/issues/578
Also: https://github.com/kubernetes/kubernetes/issues/96200

I have a possible work-around, my thought was "Is it really an error when we can't deallocate an IP? I mean... it's warning worthy, but, in the case where a pod is created, can't get assigned an IP, and then a CNI DEL comes along... it's just a warning to say I can't do that" and when I do this on CNI DEL, I instead just log an error and exit 0.

Have an experimental change in my `stuck-created` branch in this commit: https://github.com/dougbtv/whereabouts/commit/9769d4b68292eb75f4afadd9b1e0344d48e70516

**Comment by shivakumargn** [comment]
Tried this. Seems to do the job. DEL was failing to deallocate an IP that was not allocated. The success return with warning seems to be the right behavior.

**Comment by tamilselvan2086** [comment]
Doug - I face the same error in the Openshift 4.5 environment with whereabouts plugin default built in. Do we need to upgrade to latest version to recover this issue? Thanks

**Comment by dougbtv** [comment]
@tamilselvan2086 are you using the built-in whereabouts in OpenShift 4.5? It was a "tech preview" in OpenShift 4.5 -- so it's not officially supported, but you should be able to upgrade without much issue.

Otherwise, there should be fixes in 4.6+ :+1:

**Comment by GaneshVKadam** [comment]
Hello Dough,

We are facing the attached issue with multus network attachments , none of the multus PODS are comming up.
Below is the error from teh POD:

Warning FailedCreatePodSandBox 14m (x11860 over 27h) kubelet (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "4e5a8ac872e8f5ff13ef33ab71d4250959a3e8f4fb2e70c720ae27cede18e43c" network for pod "bcs01s1-prov-gls-684cc899bc-4b7j5": networkPlugin cni failed to set up pod "bcs01s1-prov-gls-684cc899bc-4b7j5_bcs01s1" network: [bcs01s1/bcs01s1-prov-gls-684cc899bc-4b7j5:n99prov]: error adding container to network "n99prov": Error at storage engine: Could not allocate IP in range: ip: 172.24.1.120 / - 172.24.1.123 / range: net.IPNet{IP:net.IP{0xac, 0x18, 0x0, 0x0}, Mask:net.IPMask{0xff, 0xff, 0xfe, 0x0}}

The NetAttach definition is attached.

Name: n99prov
Namespace: bcs01s1
Labels:
Annotations:
API Version: k8s.cni.cncf.io/v1
Kind: NetworkAttachmentDefinition
Metadata:
Creation Timestamp: 2021-10-28T19:02:23Z
Generation: 2
Managed Fields:
API Version: k8s.cni.cncf.io/v1
Fields Type: FieldsV1
fieldsV1:
f:metadata:
f:annotations:
.:
f:kubectl.kubernetes.io/last-applied-configuration:
f:spec:
Manager: kubectl-client-side-apply
Operation: Update
Time: 2021-10-28T19:02:23Z
API Version: k8s.cni.cncf.io/v1
Fields Type: FieldsV1
fieldsV1:
f:spec:
f:config:
Manager: kubectl-edit
Operation: Update
Time: 2021-10-29T23:40:18Z
Resource Version: 161026868
Self Link: /apis/k8s.cni.cncf.io/v1/namespaces/bcs01s1/network-attachment-definitions/n99prov
UID: 18e72b48-1122-47b4-94f6-0299efc28700
Spec:
Config: { "cniVersion":"0.3.1", "type":"ipvlan", "capabilities":{ "ips":true }, "master":"eth1", "ipam":{ "type":"whereabouts", "range": "172.24.0.0/23", "range_start": "172.24.1.120", "range_end": "172.24.1.123", "routes": [ { "dst": "172.24.0.0/23", "gw": "172.24.1.254" } ], "log_file" : "/tmp/whereabouts.log", "log_level" : "debug"} }
Events:

The detailed wher about logs detalls the belwo error
2021-10-29T23:40:48Z [error] Error deallocating IP: Did not find reserved IP for container 248a82d1a013fb4c9234b22ba100b6e93ee07aa5bcb32bb232f57f2cf9d2db1a

attacherd is teh wherabouts file with teh error
Whereabouts.log
[Whereabouts.zip](https://github.com/k8snetworkplumbingwg/whereabouts/files/7461710/Whereabouts.zip)

Kindly let me know which CNI version will it be corrected.
