### ISSUE TITLE
In case of IPv6 range, exclude option does not work

### ISSUE THREAD

**Issue by TothFerenc** [dougbtv/whereabouts#71]
Hello,

I use Multus with the following IPAM section:
```
  "ipam": {
   "type": "whereabouts",
   "range": "caa5::0/112",
   "exclude": ["caa5::0/113"]
  }
```
The first allocated IP should be `caa5::8000`, but whereabouts gives `caa5::1`, `caa5::2`, and so on:
```
  allocations:
    "1":
      id: 902094d529344e91128eaafdccdd280a76eaf6d96e438a5ef86b8102f8c3930c
    "2":
      id: aff8db47655d98297f6543a4656bda2a1495ddd68c7aafec8fa8a6a2611e93e1
    "3":
      id: 3597b026f196d382a43359bb735f4b6ffa9ae94c7e9e59c87a0bfef6bb1caec7
```

Does exclude work in case of IPv6 subnet?

**Comment by TothFerenc** [comment]
Hi @dougbtv !
This fix has been verified on our end, it works fine.
Can you please check and merge it if you agree?
Thanks!

**Comment by TothFerenc** [comment]
Hi Shiva! Thanks for the fix. Please create a PR in this repo (not on your fork). Thanks!

**Comment by shivakumargn** [comment]
My bad, done it right now.
