### ISSUE TITLE
Whereabouts plus Multus macvlan cni not working

### ISSUE THREAD

**Issue by Ieneya** [dougbtv/whereabouts#78]
Hi,
      I have created a cluster , installed Multus on top of it ,created network attachment definition using macvlan as per QuickStart Guide [https://github.com/intel/multus-cni]

while creating network interface in ipam section it's "host-local" which will communicate in the same node and it worked.

For communicating across nodes , I installed whereabouts but the ping didn't work as per this guide [http://dougbtv.com/nfvpe/2019/11/27/whereabouts-a-cluster-wide-cni-ipam-plugin/]

Platform: GKE 1.17.13-gke.2001 (default)
Node Platform : Ubuntu 

Many Thanks,
Ieneya

**Comment by dougbtv** [comment]
Hi @leneya could you enable logging and show us the logs? that would be quite helpful, see here: https://github.com/dougbtv/whereabouts/blob/master/doc/extended-configuration.md#logging-parameters

Also, at what point did it fail in the blog article? I think there's been some significant changes to Whereabouts since I wrote the article, would love to update it.

Also, can you show us the output of `kubectl exec your-pod-name -- ip a` as well? Thanks!

**Comment by Ieneya** [comment]
Sorry for late response @**dougbtv** 
 
I have a created a **pod** as shown below
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  namespace: kube-system
  annotations:
    k8s.v1.cni.cncf.io/networks: kube-system/whereabouts-conf1 
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: centos/tools
  nodeSelector:
    second: node2

**whereabout's config file:**
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: whereabouts-conf1
  namespace: kube-system 
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "whereaboutsexample1",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.0.0/24"
      }
    }'
Here's the **output of pod's ip**
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if20: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP group default 
    link/ether 26:7d:a4:fb:9a:2d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.100.2.13/32 scope global eth0
       valid_lft forever preferred_lft forever
4: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP group default 
    link/ether b2:e0:67:cd:18:b2 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.0.1/24 brd 192.168.0.255 scope global net1
       valid_lft forever preferred_lft forever

The pod is taking the interface net1 created using macvaln type specified with whereabouts.

But I found an issue while taking calico's log as well as flannel's log
 Note : I didn't install calico separately , I enabled GKE network policy

Here's the  **log file of calico's pod**
2020-12-14 06:08:08.010 [INFO][8] startup.go 256: Early log level set to info
2020-12-14 06:08:08.011 [INFO][8] startup.go 272: Using NODENAME environment for node name
2020-12-14 06:08:08.011 [INFO][8] startup.go 284: Determined node name: gke-multus-cluster1-default-pool-06e23df4-w6gm
2020-12-14 06:08:08.012 [INFO][8] k8s.go 219: Using host-local IPAM
2020-12-14 06:08:08.015 [INFO][8] startup.go 316: Checking datastore connection
2020-12-14 06:08:08.029 [INFO][8] startup.go 340: Datastore connection verified
2020-12-14 06:08:08.029 [INFO][8] startup.go 95: Datastore is ready
2020-12-14 06:08:08.060 [INFO][8] startup.go 682: Skipping IP pool configuration
2020-12-14 06:08:08.067 [INFO][8] startup.go 181: Using node name: gke-multus-cluster1-default-pool-06e23df4-w6gm
2020-12-14 06:08:08.089 [INFO][14] k8s.go 219: Using host-local IPAM
CALICO_NETWORKING_BACKEND is none - no BGP daemon running
Calico node started successfully
2020-12-14 06:08:09.143 [INFO][33] token_watch.go 45: Watching contents for changes. directory="/var/run/secrets/kubernetes.io/serviceaccount/"
2020-12-14 06:08:09.177 [WARNING][34] int_dataplane.go 362: Failed to query VXLAN device error=Link not found
2020-12-14 06:08:09.202 [WARNING][34] int_dataplane.go 392: Failed to cleanup preexisting XDP state error=failed to load BPF program (/tmp/felix-bpf-833862893): stat /sys/fs/bpf/calico/xdp/prefilter_v1_calico_tmp_A: no such file or directory
libbpf: failed to get EHDR from /tmp/felix-bpf-833862893
Error: failed to open object file

Here's the **log file of flannel's pod**
ERROR: logging before flag.Parse: I1214 13:49:15.536054       1 main.go:519] Determining IP address of default interface
ERROR: logging before flag.Parse: I1214 13:49:15.536918       1 main.go:532] Using interface with name eth0 and address 10.142.15.215
ERROR: logging before flag.Parse: I1214 13:49:15.536941       1 main.go:549] Defaulting external address to interface address (10.142.15.215)
W1214 13:49:15.536961       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
ERROR: logging before flag.Parse: I1214 13:49:15.555163       1 kube.go:116] Waiting 10m0s for node controller to sync
ERROR: logging before flag.Parse: I1214 13:49:15.555932       1 kube.go:299] Starting kube subnet manager
ERROR: logging before flag.Parse: I1214 13:49:16.555878       1 kube.go:123] Node controller sync successful
ERROR: logging before flag.Parse: I1214 13:49:16.556372       1 main.go:253] Created subnet manager: Kubernetes Subnet Manager - gke-multus-cluster1-default-pool-06e23df4-w6gm
ERROR: logging before flag.Parse: I1214 13:49:16.556512       1 main.go:256] Installing signal handlers
ERROR: logging before flag.Parse: I1214 13:49:16.556669       1 main.go:391] Found network config - Backend type: vxlan
ERROR: logging before flag.Parse: I1214 13:49:16.556869       1 vxlan.go:123] VXLAN config: VNI=1 Port=0 GBP=false Learning=false DirectRouting=false
ERROR: logging before flag.Parse: I1214 13:49:16.696067       1 main.go:356] Current network or subnet (10.244.0.0/16, 10.100.1.0/24) is not equal to previous one (0.0.0.0/0, 0.0.0.0/0), trying to recycle old iptables rules
ERROR: logging before flag.Parse: I1214 13:49:16.741818       1 iptables.go:174] Deleting iptables rule: -s 0.0.0.0/0 -d 0.0.0.0/0 -j RETURN
ERROR: logging before flag.Parse: I1214 13:49:16.745904       1 iptables.go:174] Deleting iptables rule: -s 0.0.0.0/0 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
ERROR: logging before flag.Parse: I1214 13:49:16.746947       1 iptables.go:174] Deleting iptables rule: ! -s 0.0.0.0/0 -d 0.0.0.0/0 -j RETURN
ERROR: logging before flag.Parse: I1214 13:49:16.748136       1 iptables.go:174] Deleting iptables rule: ! -s 0.0.0.0/0 -d 0.0.0.0/0 -j MASQUERADE --random-fully
ERROR: logging before flag.Parse: I1214 13:49:16.755044       1 main.go:306] Setting up masking rules
ERROR: logging before flag.Parse: I1214 13:49:16.755988       1 main.go:314] Changing default FORWARD chain policy to ACCEPT
ERROR: logging before flag.Parse: I1214 13:49:16.756236       1 main.go:322] Wrote subnet file to /run/flannel/subnet.env
ERROR: logging before flag.Parse: I1214 13:49:16.756369       1 main.go:326] Running backend.
ERROR: logging before flag.Parse: I1214 13:49:16.756488       1 main.go:344] Waiting for all goroutines to exit
ERROR: logging before flag.Parse: I1214 13:49:16.756625       1 vxlan_network.go:60] watching for new subnet leases
ERROR: logging before flag.Parse: I1214 13:49:16.759950       1 iptables.go:150] Some iptables rules are missing; deleting and recreating rules
ERROR: logging before flag.Parse: I1214 13:49:16.760130       1 iptables.go:174] Deleting iptables rule: -s 10.244.0.0/16 -d 10.244.0.0/16 -j RETURN
ERROR: logging before flag.Parse: I1214 13:49:16.761264       1 iptables.go:150] Some iptables rules are missing; deleting and recreating rules
ERROR: logging before flag.Parse: I1214 13:49:16.761420       1 iptables.go:174] Deleting iptables rule: -s 10.244.0.0/16 -j ACCEPT
ERROR: logging before flag.Parse: I1214 13:49:16.762467       1 iptables.go:174] Deleting iptables rule: -s 10.244.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
ERROR: logging before flag.Parse: I1214 13:49:16.763753       1 iptables.go:174] Deleting iptables rule: -d 10.244.0.0/16 -j ACCEPT
ERROR: logging before flag.Parse: I1214 13:49:16.765095       1 iptables.go:174] Deleting iptables rule: ! -s 10.244.0.0/16 -d 10.100.1.0/24 -j RETURN
ERROR: logging before flag.Parse: I1214 13:49:16.766266       1 iptables.go:162] Adding iptables rule: -s 10.244.0.0/16 -j ACCEPT
ERROR: logging before flag.Parse: I1214 13:49:16.767469       1 iptables.go:174] Deleting iptables rule: ! -s 10.244.0.0/16 -d 10.244.0.0/16 -j MASQUERADE --random-fully
ERROR: logging before flag.Parse: I1214 13:49:16.769562       1 iptables.go:162] Adding iptables rule: -s 10.244.0.0/16 -d 10.244.0.0/16 -j RETURN
ERROR: logging before flag.Parse: I1214 13:49:16.771258       1 iptables.go:162] Adding iptables rule: -d 10.244.0.0/16 -j ACCEPT
ERROR: logging before flag.Parse: I1214 13:49:16.774708       1 iptables.go:162] Adding iptables rule: -s 10.244.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
ERROR: logging before flag.Parse: I1214 13:49:16.777972       1 iptables.go:162] Adding iptables rule: ! -s 10.244.0.0/16 -d 10.100.1.0/24 -j RETURN
ERROR: logging before flag.Parse: I1214 13:49:16.780098       1 iptables.go:162] Adding iptables rule: ! -s 10.244.0.0/16 -d 10.244.0.0/16 -j MASQUERADE --random-fully

Is there a way to resolve this ?
Is it because of GKE? 

Many Thanks,
Ieneya

**Comment by dougbtv** [comment]
Hey @Ieneya -- thanks for getting back with all the logs.

So, I don't think this is necessarily a whereabouts issue, whereabouts only concern is to assign the IP address, which looks like it's happening in your output here @ 

```
4: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP group default 
    link/ether b2:e0:67:cd:18:b2 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.0.1/24 brd 192.168.0.255 scope global net1
```

The additional interface that you created won't necessarily care about what's happened with your default network, so... if there's no ping over the macvlan interface.... it's quite likely that the traffic gets filtered by GCE/GKE. I know from experience that AWS filters macvlan traffic, so... it can't make it from host-to-host over macvlan.

That's worth looking into. It may be worthwhile to file an issue for macvlan in the CNI maintainers repo: https://github.com/containernetworking/plugins
