### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by jdambly-ns** [dougbtv/whereabouts#79]
is there a well known helm chart for whereabouts?

**Comment by dougbtv** [comment]
Not yet, however, it should be as easy using the provided https://github.com/dougbtv/whereabouts/blob/master/doc/daemonset-install.yaml as a baseline.

If you have interest in creating one, I would love to have it contributed if you have any interest! Thanks!

**Comment by jdambly-ns** [comment]
I wouldn't mind creating one, let me work on a PR. Just so you know we are using multus/sriov/bond-cni/whereabouts on our baremetal clusters. we require helm charts for all our deploys so we are happy to help.

**Comment by jdambly** [comment]
@dougbtv I created PR for a helm chert here: https://github.com/k8snetworkplumbingwg/helm-charts/pull/1

if this isn't the right place let me know

**Comment by dougbtv** [comment]
Looks great! Thanks! Merged it :+1:
